### ISSUE TITLE
Set a proper CFBundleShortVersionString in the Info.plist

### ISSUE THREAD

**Issue by seanm** [ProteusMRIgHIFU/BabelBrain#39]
Currently the Info.plist contains:

```
	<key>CFBundleShortVersionString</key>
	<string>0.0.0</string>
```

Which means Finder's Get Info indeed shows the version as 0.0.0 instead of 0.2.9 (or whatever).

Also, it is customary on macOS for versions to be x.y.z, not things like "0.2.9.2-64".

**Comment by spichardo** [comment]
Thanks Sean!, addressed now in bbcc8ed
